# Funding links for Ops-Center
# These are displayed in the "Sponsor" button on GitHub

github: [Unicorn-Commander]
buy_me_a_coffee: aaronyo
# ko_fi: magicunicorn
# open_collective: ops-center
custom: ["https://unicorncommander.com"]
