#!/bin/bash
# Test API Key Generation via Admin Endpoint
# This script tests the new API key authentication system

echo "=========================================="
echo "API KEY GENERATION TEST"
echo "=========================================="
echo ""

# Step 1: Generate API key (requires admin session - run from authenticated browser)
echo "Step 1: Generate API key via admin endpoint"
echo ""
echo "Run this in your browser console (while logged in as admin):"
echo ""
echo "fetch('http://localhost:8084/api/v1/admin/users/admin@example.com/api-keys', {"
echo "  method: 'POST',"
echo "  headers: { 'Content-Type': 'application/json' },"
echo "  body: JSON.stringify({"
echo "    name: 'My First API Key',"
echo "    expires_in_days: 90,"
echo "    permissions: ['llm:inference', 'llm:models']"
echo "  })"
echo "}).then(r => r.json()).then(console.log)"
echo ""
echo "=========================================="
echo ""

# Step 2: Test with API key
echo "Step 2: After getting your API key, test it with:"
echo ""
echo "API_KEY='uc_YOUR_KEY_HERE'"
echo ""
echo "# Test models endpoint (no auth required)"
echo "curl http://localhost:8084/api/v1/llm/models | jq '.data[:3]'"
echo ""
echo "# Test chat completions (requires API key)"
echo "curl -X POST http://localhost:8084/api/v1/llm/chat/completions \\"
echo "  -H 'Authorization: Bearer \$API_KEY' \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"model\": \"openai/gpt-4o-mini\","
echo "    \"messages\": [{\"role\": \"user\", \"content\": \"Hello!\"}]"
echo "  }' | jq '.'"
echo ""
echo "=========================================="
echo ""

# Alternative: Direct database method for testing
echo "Alternative: Generate API key directly via database"
echo ""
echo "# Run this in Python (in container):"
echo "docker exec -it ops-center-direct python3 << 'PYTHON'"
echo "import asyncio"
echo "import asyncpg"
echo "from api_key_manager import APIKeyManager"
echo ""
echo "async def create_key():"
echo "    pool = await asyncpg.create_pool("
echo "        host='unicorn-postgresql',"
echo "        port=5432,"
echo "        user='unicorn',"
echo "        password='unicorn',"
echo "        database='unicorn_db'"
echo "    )"
echo "    manager = APIKeyManager(pool)"
echo "    await manager.initialize_table()"
echo "    result = await manager.create_api_key("
echo "        user_id='admin@example.com',"
echo "        key_name='CLI Generated Key',"
echo "        expires_in_days=90"
echo "    )"
echo "    print(f\"API Key: {result['api_key']}\")"
echo "    print(f\"Key ID: {result['key_id']}\")"
echo "    print(f\"Prefix: {result['key_prefix']}\")"
echo "    await pool.close()"
echo ""
echo "asyncio.run(create_key())"
echo "PYTHON"
echo ""
echo "=========================================="
