name: Forgejo CI/CD Pipeline

on:
  push:
    branches: [main, develop, staging]
  pull_request:
    branches: [main, develop]
  release:
    types: [published]

env:
  REGISTRY: git.your-domain.com
  IMAGE_NAME: unicorncommander/ops-center

jobs:
  # ============================================
  # CODE QUALITY & LINTING
  # ============================================
  code-quality:
    name: Code Quality & Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Python linting tools
        run: |
          pip install --upgrade pip
          pip install ruff black mypy bandit

      - name: Install Node dependencies
        run: npm ci

      - name: Run Ruff (Python linter)
        run: |
          cd backend
          ruff check . || true

      - name: Run Black (Python formatter check)
        run: |
          cd backend
          black --check --diff . || true

      - name: Run MyPy (Type checking)
        run: |
          cd backend
          mypy . --ignore-missing-imports --no-strict-optional || true

      - name: Run ESLint (JavaScript linter)
        run: |
          npm install -D eslint eslint-plugin-react eslint-plugin-react-hooks
          npx eslint src --ext .js,.jsx --max-warnings=100 || true

  # ============================================
  # BACKEND TESTS
  # ============================================
  backend-tests:
    name: Backend Unit & Integration Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: unicorn
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install pytest pytest-cov pytest-asyncio pytest-timeout httpx

      - name: Run unit tests
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: unicorn
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          TESTING: true
        run: |
          cd backend
          pytest tests/unit -v \
            --cov=. \
            --cov-report=xml \
            --cov-report=term-missing \
            --timeout=30 \
            || true

      - name: Run integration tests
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: unicorn
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          TESTING: true
        run: |
          cd backend
          pytest tests/integration -v \
            --cov=. \
            --cov-append \
            --cov-report=xml \
            --cov-report=term-missing \
            --timeout=60 \
            || true

  # ============================================
  # FRONTEND TESTS
  # ============================================
  frontend-tests:
    name: Frontend Tests & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        env:
          NODE_OPTIONS: '--max-old-space-size=4096'
        run: |
          npm run build

      - name: Analyze bundle size
        run: |
          du -sh dist/
          find dist -type f -exec du -h {} + | sort -rh | head -10

  # ============================================
  # DOCKER BUILD
  # ============================================
  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: [code-quality, backend-tests, frontend-tests]
    if: github.event_name == 'push' || github.event_name == 'release'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Forgejo Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.FORGEJO_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # ============================================
  # DEPLOY STAGING
  # ============================================
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: [docker-build]
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to staging server
        run: |
          echo "Deploying to staging environment"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"

  # ============================================
  # DEPLOY PRODUCTION
  # ============================================
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [docker-build]
    if: github.event_name == 'release'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to production
        run: |
          echo "Deploying to production"
          echo "Version: ${{ github.event.release.tag_name }}"
          echo "Commit: ${{ github.sha }}"
