/**
 * Critical User Paths - E2E Test Suite
 * Generated by Night Shift QA Team
 * Date: 2025-10-28
 */

const { test, expect } = require('@playwright/test');

// Test configuration
const BASE_URL = process.env.OPS_CENTER_URL || 'http://localhost:8084';
const ADMIN_USER = process.env.ADMIN_USER || 'admin';
const ADMIN_PASS = process.env.ADMIN_PASS || 'test-password-placeholder';

test.describe('Critical User Paths', () => {

  test.describe('Authentication Flow', () => {

    test('should redirect to SSO login when not authenticated', async ({ page }) => {
      await page.goto(`${BASE_URL}/admin`);

      // Should redirect to OAuth login
      await expect(page).toHaveURL(/.*auth\/login.*/);
    });

    test('should load public landing page for authenticated users', async ({ page, context }) => {
      // Simulate authenticated session
      await context.addCookies([{
        name: 'authToken',
        value: 'test-token-placeholder',
        domain: 'localhost',
        path: '/'
      }]);

      await page.goto(`${BASE_URL}/`);

      // Should load landing page (may redirect based on auth state)
      await expect(page).toHaveTitle(/Ops.*Center|Unicorn.*Commander/);
    });
  });

  test.describe('Dashboard Navigation', () => {

    test.beforeEach(async ({ page, context }) => {
      // Set up authenticated session
      await context.addCookies([{
        name: 'authToken',
        value: 'test-token-placeholder',
        domain: 'localhost',
        path: '/'
      }]);

      await page.goto(`${BASE_URL}/admin`);
    });

    test('should navigate to User Management', async ({ page }) => {
      // Click on System menu
      await page.click('text=System');

      // Click on Users submenu
      await page.click('text=Users');

      // Verify URL and page content
      await expect(page).toHaveURL(/.*admin\/system\/users.*/);
      await expect(page.locator('h1')).toContainText('User Management');
    });

    test('should navigate to Billing Dashboard', async ({ page }) => {
      await page.click('text=System');
      await page.click('text=Billing');

      await expect(page).toHaveURL(/.*admin\/system\/billing.*/);
      await expect(page.locator('h1')).toContainText(/Billing|Revenue/);
    });

    test('should navigate to Organizations', async ({ page }) => {
      await page.click('text=Organization');

      await expect(page).toHaveURL(/.*admin\/organizations.*/);
      await expect(page.locator('h1')).toContainText('Organizations');
    });

    test('should navigate to LLM Hub', async ({ page }) => {
      await page.click('text=LLM Hub');

      await expect(page).toHaveURL(/.*admin\/llm-hub.*/);
      await expect(page.locator('h1')).toContainText(/LLM|Model/);
    });

    test('should navigate to Geeses (ATLAS)', async ({ page }) => {
      // Navigate to Monitoring section
      await page.click('text=Monitoring');

      // Click Geeses link
      await page.click('text=Geeses');

      // Verify navigation
      await expect(page).toHaveURL(/.*admin\/(monitoring\/)?geeses.*/);
      await expect(page.locator('h1')).toContainText(/Geeses|ATLAS/);
    });
  });

  test.describe('User Management Operations', () => {

    test.beforeEach(async ({ page, context }) => {
      await context.addCookies([{
        name: 'authToken',
        value: 'test-token-placeholder',
        domain: 'localhost',
        path: '/'
      }]);

      await page.goto(`${BASE_URL}/admin/system/users`);
    });

    test('should display user list with metrics', async ({ page }) => {
      // Wait for user table to load
      await page.waitForSelector('table', { timeout: 5000 });

      // Verify metrics cards are present
      await expect(page.locator('text=Total Users')).toBeVisible();
      await expect(page.locator('text=Active Users')).toBeVisible();
    });

    test('should filter users by search', async ({ page }) => {
      // Type in search box
      const searchInput = page.locator('input[placeholder*="Search"]');
      await searchInput.fill('admin');

      // Wait for filtered results
      await page.waitForTimeout(500);

      // Verify table updates
      const tableRows = page.locator('tbody tr');
      await expect(tableRows).not.toHaveCount(0);
    });

    test('should filter users by tier', async ({ page }) => {
      // Open tier filter dropdown
      await page.click('text=Subscription Tier');

      // Select Professional tier
      await page.click('text=Professional');

      // Verify filter applied
      await page.waitForTimeout(500);
      const tableRows = page.locator('tbody tr');
      await expect(tableRows).toBeDefined();
    });

    test('should open user detail page on row click', async ({ page }) => {
      // Click first user row
      await page.click('tbody tr:first-child');

      // Should navigate to user detail page
      await expect(page).toHaveURL(/.*admin\/system\/users\/.+/);

      // Verify tabs are present
      await expect(page.locator('text=Overview')).toBeVisible();
      await expect(page.locator('text=Activity')).toBeVisible();
      await expect(page.locator('text=API Keys')).toBeVisible();
    });

    test('should export users to CSV', async ({ page }) => {
      // Click export button
      const [download] = await Promise.all([
        page.waitForEvent('download'),
        page.click('button:has-text("Export")')
      ]);

      // Verify download started
      expect(download.suggestedFilename()).toMatch(/users.*\.csv/);
    });
  });

  test.describe('Organization Management', () => {

    test.beforeEach(async ({ page, context }) => {
      await context.addCookies([{
        name: 'authToken',
        value: 'test-token-placeholder',
        domain: 'localhost',
        path: '/'
      }]);

      await page.goto(`${BASE_URL}/admin/organizations`);
    });

    test('should display organizations list', async ({ page }) => {
      // Verify page loaded
      await expect(page.locator('h1')).toContainText('Organizations');

      // Check for create button
      await expect(page.locator('button:has-text("Create")')).toBeVisible();
    });

    test('should open create organization modal', async ({ page }) => {
      // Click create button
      await page.click('button:has-text("Create")');

      // Verify modal appears
      await expect(page.locator('text=Create Organization')).toBeVisible();
      await expect(page.locator('input[name="name"]')).toBeVisible();
    });

    test('should validate required fields in create form', async ({ page }) => {
      await page.click('button:has-text("Create")');

      // Try to submit without filling fields
      await page.click('button:has-text("Create"):last-of-type');

      // Should show validation errors
      await expect(page.locator('text=required')).toBeVisible();
    });
  });

  test.describe('Billing & Subscription', () => {

    test.beforeEach(async ({ page, context }) => {
      await context.addCookies([{
        name: 'authToken',
        value: 'test-token-placeholder',
        domain: 'localhost',
        path: '/'
      }]);

      await page.goto(`${BASE_URL}/admin/subscription/plan`);
    });

    test('should display subscription plans', async ({ page }) => {
      // Verify plan cards
      await expect(page.locator('text=Trial')).toBeVisible();
      await expect(page.locator('text=Starter')).toBeVisible();
      await expect(page.locator('text=Professional')).toBeVisible();
      await expect(page.locator('text=Enterprise')).toBeVisible();
    });

    test('should navigate to usage page', async ({ page }) => {
      await page.click('text=Usage');

      await expect(page).toHaveURL(/.*admin\/subscription\/usage.*/);
      await expect(page.locator('text=API Calls')).toBeVisible();
    });

    test('should navigate to billing history', async ({ page }) => {
      await page.click('text=Billing');

      await expect(page).toHaveURL(/.*admin\/subscription\/billing.*/);
      await expect(page.locator('text=Invoices')).toBeVisible();
    });
  });

  test.describe('API Integration', () => {

    test('should load system status from API', async ({ page, context }) => {
      await context.addCookies([{
        name: 'authToken',
        value: 'test-token-placeholder',
        domain: 'localhost',
        path: '/'
      }]);

      await page.goto(`${BASE_URL}/admin`);

      // Wait for API call to complete
      const response = await page.waitForResponse(
        response => response.url().includes('/api/v1/system/status') && response.status() === 200
      );

      expect(response).toBeTruthy();
    });

    test('should load user analytics data', async ({ page, context }) => {
      await context.addCookies([{
        name: 'authToken',
        value: 'test-token-placeholder',
        domain: 'localhost',
        path: '/'
      }]);

      await page.goto(`${BASE_URL}/admin/system/users`);

      // Wait for analytics API call
      const response = await page.waitForResponse(
        response => response.url().includes('/api/v1/admin/users/analytics') && response.ok
      );

      expect(response).toBeTruthy();
    });
  });

  test.describe('Responsive Design', () => {

    test('should display mobile navigation on small screens', async ({ page, context }) => {
      await page.setViewportSize({ width: 375, height: 667 }); // iPhone SE

      await context.addCookies([{
        name: 'authToken',
        value: 'test-token-placeholder',
        domain: 'localhost',
        path: '/'
      }]);

      await page.goto(`${BASE_URL}/admin`);

      // Mobile menu button should be visible
      await expect(page.locator('button[aria-label*="menu"]')).toBeVisible();
    });

    test('should work on tablet viewport', async ({ page, context }) => {
      await page.setViewportSize({ width: 768, height: 1024 }); // iPad

      await context.addCookies([{
        name: 'authToken',
        value: 'test-token-placeholder',
        domain: 'localhost',
        path: '/'
      }]);

      await page.goto(`${BASE_URL}/admin/system/users`);

      // Table should be visible and scrollable
      await expect(page.locator('table')).toBeVisible();
    });
  });

  test.describe('Accessibility', () => {

    test('should have proper ARIA labels', async ({ page, context }) => {
      await context.addCookies([{
        name: 'authToken',
        value: 'test-token-placeholder',
        domain: 'localhost',
        path: '/'
      }]);

      await page.goto(`${BASE_URL}/admin`);

      // Check for ARIA landmarks
      await expect(page.locator('[role="navigation"]')).toBeVisible();
      await expect(page.locator('[role="main"]')).toBeVisible();
    });

    test('should support keyboard navigation', async ({ page, context }) => {
      await context.addCookies([{
        name: 'authToken',
        value: 'test-token-placeholder',
        domain: 'localhost',
        path: '/'
      }]);

      await page.goto(`${BASE_URL}/admin`);

      // Tab through interactive elements
      await page.keyboard.press('Tab');
      const focusedElement = await page.evaluate(() => document.activeElement.tagName);

      // Should focus on interactive element (button, link, input)
      expect(['A', 'BUTTON', 'INPUT']).toContain(focusedElement);
    });
  });

  test.describe('Error Handling', () => {

    test('should display error boundary on component crash', async ({ page, context }) => {
      await context.addCookies([{
        name: 'authToken',
        value: 'test-token-placeholder',
        domain: 'localhost',
        path: '/'
      }]);

      // Navigate to a page
      await page.goto(`${BASE_URL}/admin`);

      // Force an error by navigating to invalid route
      await page.goto(`${BASE_URL}/admin/invalid-route-12345`);

      // Should show error page or redirect
      const pageContent = await page.textContent('body');
      expect(pageContent).toBeTruthy(); // Page should still render something
    });

    test('should handle API errors gracefully', async ({ page, context }) => {
      // Mock network failure
      await page.route('**/api/v1/**', route => route.abort());

      await context.addCookies([{
        name: 'authToken',
        value: 'test-token-placeholder',
        domain: 'localhost',
        path: '/'
      }]);

      await page.goto(`${BASE_URL}/admin`);

      // Should display error message or fallback UI
      await page.waitForTimeout(2000);
      const pageContent = await page.textContent('body');
      expect(pageContent).toContain(/error|unavailable|try again/i);
    });
  });
});

/**
 * Test Run Instructions:
 *
 * 1. Install dependencies:
 *    npm install --save-dev @playwright/test
 *
 * 2. Run tests:
 *    npx playwright test tests/e2e/critical-paths.spec.js
 *
 * 3. Run tests in headed mode (see browser):
 *    npx playwright test tests/e2e/critical-paths.spec.js --headed
 *
 * 4. Run specific test:
 *    npx playwright test -g "should navigate to Geeses"
 *
 * 5. Generate test report:
 *    npx playwright test --reporter=html
 *
 * 6. Debug tests:
 *    npx playwright test --debug
 */
