#!/bin/bash
################################################################################
# API Endpoint Validation Script
# Generated by Night Shift QA Team
# Date: 2025-10-28
#
# Purpose: Validate all Ops-Center API endpoints are responding correctly
################################################################################

set -e

# Configuration
BASE_URL="${OPS_CENTER_URL:-http://localhost:8084}"
API_BASE="${BASE_URL}/api/v1"
AUTH_TOKEN="${AUTH_TOKEN:-}"
RESULTS_FILE="/tmp/api_validation_$(date +%Y%m%d_%H%M%S).json"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Counters
TOTAL_TESTS=0
PASSED_TESTS=0
FAILED_TESTS=0

# Results array
declare -a RESULTS=()

################################################################################
# Helper Functions
################################################################################

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

test_endpoint() {
    local method="$1"
    local endpoint="$2"
    local expected_status="$3"
    local description="$4"

    TOTAL_TESTS=$((TOTAL_TESTS + 1))

    log_info "Testing: $description"
    log_info "  Method: $method $endpoint"

    local headers=""
    if [ -n "$AUTH_TOKEN" ]; then
        headers="-H \"Authorization: Bearer $AUTH_TOKEN\""
    fi

    local response
    response=$(curl -s -w "\n%{http_code}" -X "$method" "$API_BASE$endpoint" $headers 2>&1 || true)

    local http_code
    http_code=$(echo "$response" | tail -1)

    local body
    body=$(echo "$response" | head -n -1)

    if [[ "$http_code" == "$expected_status"* ]] || [[ "$expected_status" == "ANY" ]]; then
        log_info "  ${GREEN}✓ PASS${NC} - HTTP $http_code"
        PASSED_TESTS=$((PASSED_TESTS + 1))
        RESULTS+=("{\"endpoint\":\"$endpoint\",\"status\":\"PASS\",\"http_code\":$http_code,\"description\":\"$description\"}")
    else
        log_error "  ${RED}✗ FAIL${NC} - Expected $expected_status, got $http_code"
        FAILED_TESTS=$((FAILED_TESTS + 1))
        RESULTS+=("{\"endpoint\":\"$endpoint\",\"status\":\"FAIL\",\"http_code\":$http_code,\"expected\":\"$expected_status\",\"description\":\"$description\"}")
    fi

    echo ""
}

################################################################################
# Test Suite
################################################################################

log_info "Starting API Endpoint Validation"
log_info "Base URL: $BASE_URL"
log_info "API Base: $API_BASE"
echo ""

# ============================================================================
# SYSTEM ENDPOINTS
# ============================================================================

echo "=== SYSTEM ENDPOINTS ==="
test_endpoint "GET" "/system/status" "200" "System status check"
test_endpoint "GET" "/system/info" "ANY" "System information"
test_endpoint "GET" "/system/health" "200" "Health check endpoint"

# ============================================================================
# AUTHENTICATION ENDPOINTS (may redirect)
# ============================================================================

echo "=== AUTHENTICATION ENDPOINTS ==="
test_endpoint "GET" "/auth/session" "ANY" "Session check (may redirect)"
test_endpoint "GET" "/auth/user" "ANY" "Get current user"

# ============================================================================
# USER MANAGEMENT ENDPOINTS (requires auth)
# ============================================================================

echo "=== USER MANAGEMENT ENDPOINTS ==="
test_endpoint "GET" "/admin/users" "ANY" "List users (requires auth)"
test_endpoint "GET" "/admin/users/analytics/summary" "ANY" "User analytics summary"
test_endpoint "GET" "/admin/users/analytics/roles" "ANY" "Role distribution"
test_endpoint "GET" "/admin/users/roles/available" "ANY" "Available roles"

# ============================================================================
# BILLING ENDPOINTS (requires auth)
# ============================================================================

echo "=== BILLING ENDPOINTS ==="
test_endpoint "GET" "/billing/plans" "ANY" "List subscription plans"
test_endpoint "GET" "/billing/subscriptions/current" "ANY" "Current user subscription"

# ============================================================================
# ORGANIZATION ENDPOINTS (requires auth)
# ============================================================================

echo "=== ORGANIZATION ENDPOINTS ==="
test_endpoint "GET" "/org/list" "ANY" "List organizations"
test_endpoint "GET" "/organizations" "ANY" "Organizations (alternative route)"

# ============================================================================
# LLM ENDPOINTS (requires auth)
# ============================================================================

echo "=== LLM ENDPOINTS ==="
test_endpoint "GET" "/llm/models" "ANY" "List LLM models"
test_endpoint "GET" "/llm/providers" "ANY" "List LLM providers"
test_endpoint "GET" "/llm/usage" "ANY" "LLM usage statistics"

# ============================================================================
# MONITORING ENDPOINTS
# ============================================================================

echo "=== MONITORING ENDPOINTS ==="
test_endpoint "GET" "/metrics" "ANY" "Prometheus metrics"
test_endpoint "GET" "/monitoring/services" "ANY" "Service status"

# ============================================================================
# TRAEFIK ENDPOINTS
# ============================================================================

echo "=== TRAEFIK ENDPOINTS ==="
test_endpoint "GET" "/traefik/status" "ANY" "Traefik status"
test_endpoint "GET" "/traefik/routes" "ANY" "Traefik routes"
test_endpoint "GET" "/traefik/services" "ANY" "Traefik services"

# ============================================================================
# INFRASTRUCTURE ENDPOINTS
# ============================================================================

echo "=== INFRASTRUCTURE ENDPOINTS ==="
test_endpoint "GET" "/cloudflare/status" "ANY" "Cloudflare integration status"
test_endpoint "GET" "/storage/status" "ANY" "Storage status"
test_endpoint "GET" "/network/interfaces" "ANY" "Network interfaces"

# ============================================================================
# ANALYTICS ENDPOINTS (requires auth)
# ============================================================================

echo "=== ANALYTICS ENDPOINTS ==="
test_endpoint "GET" "/analytics/dashboard" "ANY" "Analytics dashboard data"
test_endpoint "GET" "/analytics/revenue" "ANY" "Revenue analytics"
test_endpoint "GET" "/analytics/usage" "ANY" "Usage analytics"

# ============================================================================
# SERVICE DISCOVERY ENDPOINTS
# ============================================================================

echo "=== SERVICE DISCOVERY ENDPOINTS ==="
test_endpoint "GET" "/services/list" "ANY" "List all services"
test_endpoint "GET" "/services/status" "ANY" "Service health status"

################################################################################
# Test Results Summary
################################################################################

echo ""
echo "======================================================================="
echo "API VALIDATION TEST RESULTS"
echo "======================================================================="
echo ""
echo "Total Tests:  $TOTAL_TESTS"
echo -e "${GREEN}Passed:       $PASSED_TESTS${NC}"
echo -e "${RED}Failed:       $FAILED_TESTS${NC}"
echo ""

if [ $FAILED_TESTS -eq 0 ]; then
    echo -e "${GREEN}✓ ALL TESTS PASSED${NC}"
    exit_code=0
else
    echo -e "${RED}✗ SOME TESTS FAILED${NC}"
    exit_code=1
fi

# Calculate success rate
success_rate=$(echo "scale=2; ($PASSED_TESTS / $TOTAL_TESTS) * 100" | bc)
echo "Success Rate: ${success_rate}%"

################################################################################
# Save Results to JSON
################################################################################

echo ""
log_info "Saving results to: $RESULTS_FILE"

cat > "$RESULTS_FILE" <<EOF
{
  "timestamp": "$(date -Iseconds)",
  "base_url": "$BASE_URL",
  "total_tests": $TOTAL_TESTS,
  "passed": $PASSED_TESTS,
  "failed": $FAILED_TESTS,
  "success_rate": $success_rate,
  "results": [
    $(IFS=,; echo "${RESULTS[*]}")
  ]
}
EOF

log_info "Results saved successfully"

################################################################################
# Recommendations
################################################################################

echo ""
echo "======================================================================="
echo "RECOMMENDATIONS"
echo "======================================================================="
echo ""

if [ $FAILED_TESTS -gt 0 ]; then
    log_warn "Some endpoints failed validation. Review the following:"
    echo "  1. Ensure backend services are running"
    echo "  2. Check authentication token is valid"
    echo "  3. Verify database connections"
    echo "  4. Review backend logs for errors"
fi

if [ -z "$AUTH_TOKEN" ]; then
    log_warn "No AUTH_TOKEN provided. To test authenticated endpoints:"
    echo "  1. Login to Ops-Center via browser"
    echo "  2. Copy token from localStorage or cookies"
    echo "  3. Run: AUTH_TOKEN=your-token ./validate-endpoints.sh"
fi

echo ""
log_info "For detailed API documentation, visit:"
echo "  ${BASE_URL}/admin/platform/api-docs"

echo ""
log_info "To view results with jq:"
echo "  cat $RESULTS_FILE | jq ."

echo ""

exit $exit_code
