"""initial schema baseline

Revision ID: f6570c470a28
Revises: 
Create Date: 2025-10-23 00:07:11.175157+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6570c470a28'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_status'), 'audit_logs', ['status'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('cloudflare_domains',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('domain_name', sa.String(length=255), nullable=False),
    sa.Column('domain_id', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('zone_id', sa.String(length=255), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cloudflare_domains_domain_name'), 'cloudflare_domains', ['domain_name'], unique=True)
    op.create_index(op.f('ix_cloudflare_domains_expiration_date'), 'cloudflare_domains', ['expiration_date'], unique=False)
    op.create_index(op.f('ix_cloudflare_domains_user_id'), 'cloudflare_domains', ['user_id'], unique=False)
    op.create_table('cloudflare_zones',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('zone_id', sa.String(length=255), nullable=False),
    sa.Column('zone_name', sa.String(length=255), nullable=False),
    sa.Column('account_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('name_servers', sa.JSON(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cloudflare_zones_status'), 'cloudflare_zones', ['status'], unique=False)
    op.create_index(op.f('ix_cloudflare_zones_zone_id'), 'cloudflare_zones', ['zone_id'], unique=True)
    op.create_index(op.f('ix_cloudflare_zones_zone_name'), 'cloudflare_zones', ['zone_name'], unique=False)
    op.create_table('migration_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('domain_name', sa.String(length=255), nullable=False),
    sa.Column('source_registrar', sa.String(length=100), nullable=False),
    sa.Column('target_registrar', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'ROLLED_BACK', name='migrationstatus'), nullable=False),
    sa.Column('auth_code', sa.String(length=255), nullable=True),
    sa.Column('initiated_by', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_migration_jobs_created_at'), 'migration_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_migration_jobs_domain_name'), 'migration_jobs', ['domain_name'], unique=False)
    op.create_index(op.f('ix_migration_jobs_status'), 'migration_jobs', ['status'], unique=False)
    op.create_table('namecheap_domains',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('domain_name', sa.String(length=255), nullable=False),
    sa.Column('domain_id', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('whois_guard', sa.Boolean(), nullable=True),
    sa.Column('nameservers', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_namecheap_domains_domain_name'), 'namecheap_domains', ['domain_name'], unique=True)
    op.create_index(op.f('ix_namecheap_domains_expiration_date'), 'namecheap_domains', ['expiration_date'], unique=False)
    op.create_index(op.f('ix_namecheap_domains_user_id'), 'namecheap_domains', ['user_id'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_created_at'), 'organizations', ['created_at'], unique=False)
    op.create_index(op.f('ix_organizations_is_active'), 'organizations', ['is_active'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_created_at'), 'api_keys', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_keys_expires_at'), 'api_keys', ['expires_at'], unique=False)
    op.create_index(op.f('ix_api_keys_is_active'), 'api_keys', ['is_active'], unique=False)
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_organization_id'), 'api_keys', ['organization_id'], unique=False)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('cloudflare_dns_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('zone_id', sa.String(length=255), nullable=False),
    sa.Column('record_id', sa.String(length=255), nullable=False),
    sa.Column('record_type', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('proxied', sa.Boolean(), nullable=True),
    sa.Column('ttl', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['cloudflare_zones.zone_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cloudflare_dns_records_name'), 'cloudflare_dns_records', ['name'], unique=False)
    op.create_index(op.f('ix_cloudflare_dns_records_record_id'), 'cloudflare_dns_records', ['record_id'], unique=True)
    op.create_index(op.f('ix_cloudflare_dns_records_record_type'), 'cloudflare_dns_records', ['record_type'], unique=False)
    op.create_index(op.f('ix_cloudflare_dns_records_zone_id'), 'cloudflare_dns_records', ['zone_id'], unique=False)
    op.create_table('cloudflare_firewall_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('zone_id', sa.String(length=255), nullable=False),
    sa.Column('rule_id', sa.String(length=255), nullable=False),
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('expression', sa.Text(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['cloudflare_zones.zone_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cloudflare_firewall_rules_enabled'), 'cloudflare_firewall_rules', ['enabled'], unique=False)
    op.create_index(op.f('ix_cloudflare_firewall_rules_rule_id'), 'cloudflare_firewall_rules', ['rule_id'], unique=True)
    op.create_index(op.f('ix_cloudflare_firewall_rules_zone_id'), 'cloudflare_firewall_rules', ['zone_id'], unique=False)
    op.create_table('organization_invitations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', name='organizationmemberrole'), nullable=False),
    sa.Column('invited_by', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'EXPIRED', name='invitationstatus'), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_invitations_email'), 'organization_invitations', ['email'], unique=False)
    op.create_index(op.f('ix_organization_invitations_expires_at'), 'organization_invitations', ['expires_at'], unique=False)
    op.create_index(op.f('ix_organization_invitations_organization_id'), 'organization_invitations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_invitations_status'), 'organization_invitations', ['status'], unique=False)
    op.create_index(op.f('ix_organization_invitations_token'), 'organization_invitations', ['token'], unique=True)
    op.create_table('organization_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', name='organizationmemberrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_members_organization_id'), 'organization_members', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_members_user_id'), 'organization_members', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organization_members_user_id'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_organization_id'), table_name='organization_members')
    op.drop_table('organization_members')
    op.drop_index(op.f('ix_organization_invitations_token'), table_name='organization_invitations')
    op.drop_index(op.f('ix_organization_invitations_status'), table_name='organization_invitations')
    op.drop_index(op.f('ix_organization_invitations_organization_id'), table_name='organization_invitations')
    op.drop_index(op.f('ix_organization_invitations_expires_at'), table_name='organization_invitations')
    op.drop_index(op.f('ix_organization_invitations_email'), table_name='organization_invitations')
    op.drop_table('organization_invitations')
    op.drop_index(op.f('ix_cloudflare_firewall_rules_zone_id'), table_name='cloudflare_firewall_rules')
    op.drop_index(op.f('ix_cloudflare_firewall_rules_rule_id'), table_name='cloudflare_firewall_rules')
    op.drop_index(op.f('ix_cloudflare_firewall_rules_enabled'), table_name='cloudflare_firewall_rules')
    op.drop_table('cloudflare_firewall_rules')
    op.drop_index(op.f('ix_cloudflare_dns_records_zone_id'), table_name='cloudflare_dns_records')
    op.drop_index(op.f('ix_cloudflare_dns_records_record_type'), table_name='cloudflare_dns_records')
    op.drop_index(op.f('ix_cloudflare_dns_records_record_id'), table_name='cloudflare_dns_records')
    op.drop_index(op.f('ix_cloudflare_dns_records_name'), table_name='cloudflare_dns_records')
    op.drop_table('cloudflare_dns_records')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_organization_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_is_active'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_expires_at'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_created_at'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_is_active'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_created_at'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_namecheap_domains_user_id'), table_name='namecheap_domains')
    op.drop_index(op.f('ix_namecheap_domains_expiration_date'), table_name='namecheap_domains')
    op.drop_index(op.f('ix_namecheap_domains_domain_name'), table_name='namecheap_domains')
    op.drop_table('namecheap_domains')
    op.drop_index(op.f('ix_migration_jobs_status'), table_name='migration_jobs')
    op.drop_index(op.f('ix_migration_jobs_domain_name'), table_name='migration_jobs')
    op.drop_index(op.f('ix_migration_jobs_created_at'), table_name='migration_jobs')
    op.drop_table('migration_jobs')
    op.drop_index(op.f('ix_cloudflare_zones_zone_name'), table_name='cloudflare_zones')
    op.drop_index(op.f('ix_cloudflare_zones_zone_id'), table_name='cloudflare_zones')
    op.drop_index(op.f('ix_cloudflare_zones_status'), table_name='cloudflare_zones')
    op.drop_table('cloudflare_zones')
    op.drop_index(op.f('ix_cloudflare_domains_user_id'), table_name='cloudflare_domains')
    op.drop_index(op.f('ix_cloudflare_domains_expiration_date'), table_name='cloudflare_domains')
    op.drop_index(op.f('ix_cloudflare_domains_domain_name'), table_name='cloudflare_domains')
    op.drop_table('cloudflare_domains')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_status'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
